include: package:ubuntu_lints/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.pb*.dart"

linter:
  rules:
    - avoid_manual_providers_as_generated_provider_dependency: false