name: desktop-security-center
base: core22
version: git
summary: Desktop Security Center
description: Security Center UI for the desktop
source-code: https://github.com/canonical/desktop-security-center.git
issues: https://github.com/canonical/desktop-security-center/issues
license: GPL-3.0
grade: stable
confinement: strict
compression: lzo

apps:
  desktop-security-center:
    command: bin/security_center
    extensions: [gnome]
    plugs:
      - network
      - snapd-control
      - snap-fde-control
      - removable-media

parts:
  fvm:
    plugin: nil
    source: scripts/fvm
    override-build: |
      bash $CRAFT_PART_SRC/install.sh
    build-packages:
      - clang
      - cmake
      - curl
      - git
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ""

  security-center:
    after: [fvm]
    plugin: nil
    source: .
    override-build: |
      set -eux
      fvm install
      fvm dart pub global activate melos
      fvm dart pub global run melos clean
      fvm dart pub global run melos bootstrap

      fvm dart pub global run melos exec -c 1 --fail-fast --depends-on=build_runner -- \
      fvm dart run build_runner build --delete-conflicting-outputs

      cd packages/security_center
      fvm flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
      cd ../../
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/icons/hicolor/scalable/apps
      cp snap.desktop-security-center.Canonical.svg  $CRAFT_PART_INSTALL/meta/gui/icons/hicolor/scalable/apps
