name: desktop-security-center
version: git
summary: Desktop Security Center
description: Secutiry Center UI for the desktop
confinement: strict
base: core22
grade: stable
compression: lzo

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.16.9
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  desktop-security-center:
    after: [ flutter-git ]
    plugin: nil
    source: ./packages/desktop_security_center/
    override-build: |
      # when building locally artifacts can pollute the container and cause builds to fail
      # this helps increase reliability for local builds
      flutter clean
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
      # cp $CRAFT_PART_INSTALL/bin/data/flutter_assets/assets/firmware-updater.desktop $CRAFT_PART_INSTALL/bin/data/flutter_assets/assets/firmware-updater-app.desktop
      # echo "NoDisplay=true" >> $CRAFT_PART_INSTALL/bin/data/flutter_assets/assets/firmware-updater-app.desktop

apps:
  desktop-security-center:
    command: bin/desktop_security_center
    extensions: [gnome]
